Repository NomicFoundation/edr, pull requests merged in 2024-04, with the labels that each got.

#404 Remove add-issue-to-project workflow
  .github/workflows/add-issue-to-project.yml
Labels: no changeset needed

#395 test: add tests for calculating block timestamp
  Cargo.lock
  crates/edr_napi/src/provider.rs
  crates/edr_provider/Cargo.toml
  crates/edr_provider/src/console_log.rs
  crates/edr_provider/src/data.rs
  crates/edr_provider/src/error.rs
  crates/edr_provider/src/interval.rs
  crates/edr_provider/src/lib.rs
  crates/edr_provider/src/requests/debug.rs
  crates/edr_provider/src/requests/eth/accounts.rs
  crates/edr_provider/src/requests/eth/blockchain.rs
  crates/edr_provider/src/requests/eth/blocks.rs
  crates/edr_provider/src/requests/eth/call.rs
  crates/edr_provider/src/requests/eth/config.rs
  crates/edr_provider/src/requests/eth/evm.rs
  crates/edr_provider/src/requests/eth/filter.rs
  crates/edr_provider/src/requests/eth/gas.rs
  crates/edr_provider/src/requests/eth/mine.rs
  crates/edr_provider/src/requests/eth/sign.rs
  crates/edr_provider/src/requests/eth/state.rs
  crates/edr_provider/src/requests/eth/transactions.rs
  crates/edr_provider/src/requests/hardhat/accounts.rs
  crates/edr_provider/src/requests/hardhat/config.rs
  crates/edr_provider/src/requests/hardhat/log.rs
  crates/edr_provider/src/requests/hardhat/miner.rs
  crates/edr_provider/src/requests/hardhat/state.rs
  crates/edr_provider/src/requests/hardhat/transactions.rs
  crates/edr_provider/src/time.rs
  crates/edr_provider/tests/issue_324.rs
  crates/edr_provider/tests/issue_325.rs
  crates/edr_provider/tests/issue_326.rs
  crates/edr_provider/tests/issue_346.rs
  crates/edr_provider/tests/issue_356.rs
  crates/edr_provider/tests/issue_361.rs
  crates/edr_provider/tests/issue_384.rs
  crates/edr_provider/tests/timestamp.rs
  crates/tools/src/scenario.rs
Labels: no changeset needed

#397 ci: add Anvil option to JS benchmark runner
  crates/tools/js/benchmark/README.md
  crates/tools/js/benchmark/index.js
  crates/tools/js/benchmark/package.json
  pnpm-lock.yaml
Labels: no changeset needed

#413 Update repository in package.json files
  crates/edr_napi/npm/darwin-arm64/package.json
  crates/edr_napi/npm/darwin-x64/package.json
  crates/edr_napi/npm/linux-arm64-gnu/package.json
  crates/edr_napi/npm/linux-arm64-musl/package.json
  crates/edr_napi/npm/linux-x64-gnu/package.json
  crates/edr_napi/npm/linux-x64-musl/package.json
  crates/edr_napi/npm/win32-x64-msvc/package.json
  crates/edr_napi/package.json
Labels: no changeset needed

#415 Don't use latest os in the edr-npm-release workflow
  .github/workflows/edr-npm-release.yml
Labels: type: ci, no changeset needed

#419 edr-0.3.7-rc.0
  crates/edr_napi/package.json
Labels: no changeset needed

#420 edr-0.3.7
  crates/edr_napi/package.json
Labels: no changeset needed

#423 docs: add instructions for profiling with perf/DTrace
  book/src/01_getting_started/05_profiling.md
Labels: no changeset needed

#424 refactor: use alloy_primitives::TxKind
  crates/edr_eth/src/transaction.rs
  crates/edr_eth/src/transaction/kind.rs
  crates/edr_eth/src/transaction/request/eip155.rs
  crates/edr_eth/src/transaction/request/eip1559.rs
  crates/edr_eth/src/transaction/request/eip2930.rs
  crates/edr_eth/src/transaction/request/legacy.rs
  crates/edr_eth/src/transaction/signed.rs
  crates/edr_eth/src/transaction/signed/eip155.rs
  crates/edr_eth/src/transaction/signed/eip1559.rs
  crates/edr_eth/src/transaction/signed/eip2930.rs
  crates/edr_eth/src/transaction/signed/legacy.rs
  crates/edr_evm/src/test_utils.rs
  crates/edr_evm/src/transaction/executable.rs
  crates/edr_evm/tests/blockchain.rs
  crates/edr_provider/src/console_log.rs
  crates/edr_provider/src/data.rs
  crates/edr_provider/src/requests/eth/transactions.rs
Labels: type: refactor, no changeset needed
